# Main client menu printout
def print_menu():
    #print("\n", 36 * "-", "MENU", 36 * "-")
    #print("1. RETRIEVE student images and ENCODE faces")
    #print("2. TAKE automatic ATTENDANCE")
    #print("3. Enter attendance MANUALLY (MySQL)")
    #print("4. Get ALL attendance data (MySQL)")
    #print("5. Get attendance data BY LESSON ID (MySQL)")
    #print("6. Get attendance data BY STUDENT ID (MySQL)")
    #print("7. Get information about today's lessons BY AUDITORIUM (MySQL)")
    #print("8. Exit SATS")
    print("\n", 36 * "-", "Izvēlne", 36 * "-")
    print("1. IEGŪT pieejamās studentu bildes un tās KODĒT")
    print("2. Sākt automātisko apmeklējuma reģistrāciju")
    print("3. Ievadīt apmeklējuma informāciju MANUĀLI (MySQL)")
    print("4. Iegūt informāciju par VISIEM apmeklējumiem (MySQL)")
    print("5. Iegūt apmeklējuma informāciju izvēlētajai NODARBĪBAI (MySQL)")
    print("6. Iegūt apmeklējuma informāciju izvēlētajam STUDENTAM (MySQL)")
    print("7. Iegūt informāciju par šodienas nodarbībām izvēlētajā TELPĀ (MySQL)")
    print("8. Iziet no SATS")
    print(79 * "-")